services:
  mongo:
    image: mongo:7
    container_name: MongoDB
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh --quiet | grep 1
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 20s
    volumes:
      - "material-cms-dev-mongo-data:/data/db"
      - "material-cms-dev-mongo-configdb:/data/configdb"
    ports:
      - "27017:27017"

  redis:
    image: redis
    command: redis-server
    container_name: Redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 5s
    ports:
      - "6379:6379"

volumes:
  material-cms-dev-mongo-data:
  material-cms-dev-mongo-configdb:
